apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disp-time-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: disp-time-ip
    networking.gke.io/managed-certificates: disp-time-cert
    networking.gke.io/v1beta1.FrontendConfig: disp-time-frontend-config
spec:
  defaultBackend:
    service:
      name: disp-time-service
      port:
        number: 80
