apiVersion: v1
kind: Secret
metadata:
  name: disp-time-secrets
type: Opaque
data:
  # Values must be Base64 encoded!
  # e.g. echo -n "your_api_key" | base64
  OPENWEATHER_API_KEY: "WU9VUl9CQVNFNjRfRU5DT0RFRF9BUElfS0VZX0hFUkU=" # Placeholder for "YOUR_BASE64_ENCODED_API_KEY_HERE"
