apiVersion: v1
kind: Service
metadata:
  name: disp-time-service
spec:
  type: LoadBalancer
  selector:
    app: disp-time-web
  ports:
    - protocol: TCP
      port: 80        # External port (Browser hits this)
      targetPort: 19563 # Container port
